name: CI and Deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-scan:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build api-py (light)
              run: |
                  docker build --pull -t nargis-api-py:ci --build-arg BUILD_ML=0 ./apps/api-py

            - name: Build api-go
              run: |
                  docker build -t nargis-api-go:ci ./apps/api-go

            - name: Trivy scan api-py
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nargis-api-py:ci

            - name: Trivy scan api-go
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nargis-api-go:ci

    deploy:
        runs-on: ubuntu-latest
        needs: build-and-scan
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - name: Install flyctl
              run: curl -L https://fly.io/install.sh | sh
            - name: Deploy api-py to Fly
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              run: |
                  cd apps/api-py
                  flyctl deploy --config fly.toml --remote-only
            - name: Deploy api-go to Fly
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              run: |
                  cd apps/api-go
                  flyctl deploy --config fly.toml --remote-only
