name: CI Build & Publish

on:
    push:
        branches: [main, feature/**]
    pull_request:
        branches: [main]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build api-py (light)
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/api-py
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/nargis-api-py:light-${{ github.sha }}
                  build-args: |
                      BUILD_ML=0

            - name: Build api-go
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/api-go
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/nargis-api-go:latest

            - name: Run smoke test (api-py)
              uses: addnab/docker-run-action@v3
              with:
                  image: ghcr.io/${{ github.repository_owner }}/nargis-api-py:light-${{ github.sha }}
                  options: -p 8000:8000 --health-cmd="curl -sSf http://localhost:8000/health || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

            - name: Smoke check endpoint
              run: |
                  sleep 2
                  curl -fSLO http://localhost:8000/health || (cat /tmp/docker-run.log && exit 1)
