name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This ensures that both frontend and backend validation passed in the PR before this can run
    # (assuming you set up branch protection rules in GitHub).
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy Python Orchestrator to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd apps/api-py # Use the renamed folder
          flyctl deploy --remote-only

      - name: Deploy Go Gateway to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd apps/gateway # Use the renamed folder
          flyctl deploy --remote-only
